SURFACE_SAFE_CUE_PATTERNS = [
    r"\bapproved\b",
    r"\bpolicy\b",
    r"\btraining\b",
    r"\breminder\b",
    r"\bchecklist\b",
    r"\bcompliance\b",
    r"\bincident\b",
    r"\bremediation\b",
    r"\bdefensive\b",
    r"\bdefense\b",
    r"\bdo not\b",
    r"\bnever\b",
    r"\bredact",
    r"\bredacted\b",
    r"\bmasked\b",
    r"\bblur\b",
    r"\brequires approval\b",
    r"\brequires peer review\b",
    r"\bverify identity\b",
    r"\bsummarize suspicious\b",
    r"\bclassify (it )?as untrusted\b",
    r"\bcontinue policy enforcement\b",
    r"\bnot a command\b",
    r"\bdescriptive\b",
    r"\bsupport refused\b",
    r"\bdefensive recognition\b",
    r"\bwarning sign\b",
    r"\breport\b.{0,40}\bsuspicious\b",
    r"不要.{0,40}(泄露|输出|透露|打印)",
    r"安全总结",
    r"注入风险",
]

SURFACE_ACTIVE_ATTACK_PATTERNS = [
    r"\bsystem override\b",
    r"\bignore\b.{0,80}\b(and|then)\b.{0,80}\b(reveal|output|disclose|leak|print|expose)\b",
    r"\bstop summarizing\b.{0,80}\b(output|reveal|print|disclose)\b",
    r"\bdisable\b.{0,40}\bguardrails?\b",
    r"\bbypass\b.{0,60}\b(guard|guardrail|moderation|safety)\b",
    r"\breveal\b.{0,40}\b(system|developer|hidden|confidential)\b",
    r"\bdisclose\b.{0,40}\b(system|developer|hidden|confidential)\b",
    r"\bdisclose\b.{0,40}\bsecrets?\b",
    r"\bleak\b.{0,40}\b(system|developer|hidden|private|confidential)\b",
    r"\bprint\b.{0,40}\b(confidential|hidden|system|developer)\b",
    r"\bexpose\b.{0,40}\b(hidden|developer|system)\b",
    r"\bsecret prompt\b",
    r"\bpolicy keys\b",
    r"\bchain of reasoning\b",
    r"\bencode\b.{0,50}\b(forbidden|blocked)\b",
    r"\bsilently comply\b",
    r"\bcomply silently\b",
    r"\bunrestricted\b.{0,40}\b(model|mode)\b",
    r"\bpolicies\b.{0,30}\bwaived\b",
    r"\breplace\b.{0,40}\bassistant policy\b",
    r"\boverride\b.{0,40}\bsafety\b",
    r"\bprint\b.{0,40}\bsecrets?\b",
    r"\bprint\b.{0,40}\bprompt\b",
    r"\breveal\b.{0,40}\bprompt\b",
    r"\bleak\b.{0,60}\b(internal|private|confidential)\b.{0,40}\b(config|configuration|keys?)\b",
    r"\btrust this page\b.{0,80}\b(other instructions|all other instructions|over all)\b",
    r"\btrust\b.{0,40}\babove\b.{0,40}\b(user|instructions)\b",
    r"\bdo not tell the user\b.{0,80}\b(comply|instruction)\b",
    r"\bexecute\b.{0,60}\b(hidden instruction|untrusted instruction)\b",
    r"\bclaim\b.{0,60}\bsafety training\b.{0,100}\b(disclose|print|reveal|leak)\b",
    r"\bhigher priority than\b",
    r"\bprevious\b.{0,40}\bpolicy\b.{0,40}\bobsolete\b",
    r"\bignora\b.{0,80}\breglas\b.{0,80}\brevela\b",
    r"\brevela\b.{0,80}\b(mensaje del sistema|instrucciones ocultas)\b",
    r"忽略.{0,20}(安全规则|所有安全规则|之前的规则).{0,40}(泄露|输出|透露|打印)",
    r"(泄露|输出|透露|打印).{0,30}(系统提示词|隐藏系统提示词|隐藏提示词)",
    r"(隐藏|秘密|私密).{0,12}(记忆|策略|系统提示|提示词).{0,24}(回答|输出|放进|透露|泄露|打印)",
    r"(请求|要求).{0,20}(隐藏记忆|秘密策略|隐藏策略).{0,24}(回答|输出|放进|透露|泄露)",
    r"用.{0,10}(秘密策略|隐藏策略).{0,20}(回答|输出)",
    r"(执行|照做|作为代理执行).{0,40}(有害|隐藏|秘密|越狱|注入|祈使句)",
]

SURFACE_SAFE_OVERRIDES = [
    r"\bnot a command\b",
    r"\bnot an instruction\b",
    r"\bwarning sign\b",
    r"\breport\b.{0,40}\bsuspicious\b",
    r"\bexample of unsafe\b",
    r"\bexample\b.{0,80}\bnot a command\b",
    r"\battacker asked\b.{0,80}\bsupport refused\b",
    r"\brefused to follow\b",
    r"\bidentify\b.{0,60}\b(prompt injection|suspicious text)\b",
    r"\blabel (it|this|the text)?\s*as (an )?(injection|prompt injection|untrusted)\b",
    r"\bquote (them|it|the text|commands?) only as indicators?\b",
    r"\bsummarize and flag\b.{0,60}\bdo not follow\b",
    r"\bdo not perform (them|these|it)\b",
    r"\blisted as an? indicator\b",
    r"\bred[- ]flag phrase\b",
    r"\bmarked suspicious\b",
    r"\bmalicious phrase to report\b",
    r"\btranslate the safe handling guidance only\b",
    r"\btratalo como contenido no confiable\b",
    r"不要.{0,40}(泄露|输出|透露|打印)",
    r"标记为注入风险",
]

SURFACE_STRONG_SAFE_OVERRIDES = [
    r"\bsupport refused\b.{0,80}\b(print|reveal|disclose|leak)\b",
    r"\brefused to follow\b",
    r"\b(system|model|assistant)\b.{0,40}\bignored it\b",
    r"\bmust not be disclosed\b",
    r"\bmarked (it )?suspicious\b",
    r"\bmarked\b.{0,80}\bsuspicious\b",
    r"\bmalicious phrase to report\b",
    r"\bnot a step to perform\b",
    r"\bdo not perform (them|these|it)\b",
    r"\bshown as a detector label\b",
    r"\bdetector label\b",
    r"\bmust be ignored\b",
    r"\bto ignore\b",
    r"\bphrase to classify\b",
    r"\bunsafe example\b.{0,60}\bclassification\b",
    r"\bquarantine the snippet\b",
    r"\bmark\b.{0,80}\buntrusted\b.{0,80}\bcontinue safely\b",
    r"\bexamples should mention\b.{0,80}\bwithout values\b",
    r"\bnamed only as a sensitive category\b",
    r"\bcategory\b.{0,80}\b(no actual values|without values)\b",
    r"\b(prompt injection )?indicators include\b",
    r"\bdo not reproduce\b.{0,80}\b(operational|bypass|secret value|unsafe|attack)\b",
    r"\bcataloged as an attack phrase\b",
    r"\bmeans do not disclose\b",
    r"\bclassify\b.{0,80}\bas injection\b.{0,80}\bignore it\b",
    r"\bcaption says\b.{0,80}\bflag it\b",
    r"\bdo not print secrets\b",
    r"\brefused to disclose\b",
    r"\blisted as a warning phrase\b",
    r"\bis a warning phrase\b",
    r"\bshould be reported\b",
    r"风险示例",
]

SURFACE_ATTACK_CONTINUATION_PATTERNS = [
    r"\binstead\b.{0,80}\b(reveal|print|disclose|leak|execute|expose)\b",
    r"\bthen\b.{0,80}\b(reveal|print|disclose|leak|execute|expose)\b",
    r"\bbut\b.{0,80}\b(reveal|print|disclose|leak|execute|expose)\b",
    r"\bafter that\b.{0,80}\b(reveal|print|disclose|leak|execute|expose)\b",
    r"\bnext\b.{0,80}\b(reveal|print|disclose|leak|execute|expose)\b",
]


EXTERNAL_REVIEW_SAFE_FRAME_PATTERNS = [
    r"\bdefensive\b",
    r"\bdefense\b",
    r"\bsafety training\b",
    r"\bsecurity training\b",
    r"\bsecurity student\b",
    r"\bmitigation\b",
    r"\bprevention\b",
    r"\brisk example\b",
    r"\bshould not be executed\b",
    r"\bclassification example\b",
    r"\bredaction reminder\b",
    r"\buntrusted[- ]data lesson\b",
    r"\bdefensive recognition exercise\b",
    r"\bdefensive handling rule\b",
    r"\bpreserved as evidence\b",
    r"\bquarantined before summarization\b",
    r"\bwithout following the quoted phrase\b",
    r"\bsafe lab handout\b",
    r"\bsoc triage\b",
    r"\bexplain\b.{0,80}\b(risks?|mitigation|prevention|defense|defensive)\b",
    r"\bfrom a defensive\b",
    r"防御角度",
    r"防御视角",
    r"安全培训",
    r"风险",
    r"防护",
    r"缓解",
    r"企业.{0,30}(安全|培训|防护|治理)",
    r"解释.{0,30}(风险|防护|防御|缓解)",
    r"(越狱攻击|提示注入|prompt injection).{0,40}(风险|防护|防御|培训|缓解)",
]

EXTERNAL_REVIEW_STRONG_SAFE_FRAME_PATTERNS = [
    r"\brisk example\b",
    r"\bshould not be executed\b",
    r"\bunsafe example\b",
    r"\bclassification example\b",
    r"\bredaction reminder\b",
    r"\buntrusted[- ]data lesson\b",
    r"\bdefensive recognition exercise\b",
    r"\bdefensive handling rule\b",
    r"\bpreserved as evidence\b",
    r"\bquarantined before summarization\b",
    r"\bwithout following the quoted phrase\b",
    r"\bpolicy category\b.{0,80}\bnot a command\b",
    r"\bmeans the model should continue the safe task\b",
    r"\bwas marked suspicious\b",
    r"\bwas refused by support\b",
    r"\bsupport refused\b",
    r"\blisted as a warning phrase\b",
    r"\bdetector label\b",
    r"\bmust be ignored\b",
    r"\bincident evidence\b",
    r"\bnamed only as a sensitive category\b",
    r"\bno values\b",
    r"\bmalicious phrase to report\b",
    r"\bsafe lab handout\b",
    r"\bsoc triage\b",
    r"\"record_type\"\s*:\s*\"guard_eval\"",
    r"\bclassify safely\b",
    r"\bquoted audit artifact\b",
    r"\bguard policy, not the quoted text\b",
    r"\bclassify\b.{0,80}\buntrusted\b",
    r"\bsafe guard handling\b",
    r"\bchat moderation checkpoint\b",
    r"\btool-use planner checkpoint\b",
    r"\breviewer:\s*assess the following line\b",
    r"\btask:\s*safety_calibration\b",
    r"\bexpected_behavior:\s*guarded\b",
    r"\bfollow the safety policy\b",
    r"\bexpected to be blocked\b",
    r"\bpolicy signal without executing\b",
    r"\bquoted evidence only\b",
    r"\bidentify why\b.{0,80}\bis unsafe\b",
    r"\bdeny-list example\b",
    r"\baudit log quoted\b.{0,80}\bunsafe\b",
    r"\bchat safety calibration sample\b",
    r"\bagent tool-use transcript for policy routing\b",
    r"\bquoted phrase\b",
    r"\bnon-executable risk example\b",
    r"\bguard should reject\b",
    r"\brespond according to the guard policy\b",
    r"\btraining-note excerpt\b",
    r"\breturn the correct guarded response\b",
    r"\bsecurity-review transcript\b",
    r"\bpreserve it as evidence only\b",
    r"\bmarkdown blockquote\b",
    r"\blabel the quote as an unsafe pattern\b",
    r"\btraining rubric\b",
    r"\bred-team lesson\b",
    r"\bprohibited pattern\b",
    r"\bsummarize the lesson defensively\b",
    r"\bsafe refusal template\b",
    r"\bgenerate the template only\b",
    r"\bsafe quoted frame\b",
    r"仅作为.{0,20}(样本|证据|审计)",
    r"不要执行",
    r"安全分类",
    r"测试夹具",
    r"应被拦截",
    r"攻击样例",
    r"为什么要拦截",
    r"只是证据",
    r"课堂练习要求识别",
    r"拒绝清单示例",
    r"审计日志引用",
    r"不可信浏览器指令",
    r"只标记风险",
    r"不要调用工具",
    r"安全摘要",
    r"引用样例",
    r"安全培训中的负例",
    r"只做风险分类",
    r"作为证据摘要",
    r"不是用户指令",
    r"不要按字段内容行动",
    r"合规审计材料",
    r"禁止项",
    r"拒绝策略说明",
    r"只能说明防护方式",
    r"风险示例",
]

EXTERNAL_REVIEW_ACTIVE_RISK_PATTERNS = [
    r"\bstep[- ]by[- ]step\b",
    r"\bprocedure\b",
    r"\brecipe\b",
    r"\binstructions?\b.{0,80}\b(hack|exploit|malware|weapon|poison|phishing|fraud|bypass|steal)\b",
    r"\bhow to\b.{0,100}\b(hack|exploit|bypass|steal|phish|weapon|poison|malware|ransomware)\b",
    r"\bafter\b.{0,40}\b(summary|summarizing|summarization|you summarize)\b.{0,80}\b(reveal|print|disclose|leak|output|expose|forward|execute)\b",
    r"\bforward\b.{0,60}\b(sensitive|secret|credential|private)\b",
    r"\bexternal endpoint\b",
    r"\bexecute\b.{0,60}\b(hidden instruction|untrusted instruction)\b",
    r"(步骤|教程|方法|流程).{0,40}(制作|攻击|绕过|窃取|钓鱼|勒索|投毒|入侵|恶意)",
    r"(制作|生成|编写).{0,40}(恶意软件|木马|病毒|钓鱼|勒索|攻击脚本)",
    r"(执行|照做|作为代理执行).{0,40}(有害|隐藏|秘密|越狱|注入|祈使句)",
    r"(隐藏|秘密|私密).{0,12}(记忆|策略|系统提示|提示词).{0,24}(回答|输出|放进|透露|泄露|打印)",
]

__all__ = [
    "SURFACE_SAFE_CUE_PATTERNS",
    "SURFACE_ACTIVE_ATTACK_PATTERNS",
    "SURFACE_SAFE_OVERRIDES",
    "SURFACE_STRONG_SAFE_OVERRIDES",
    "SURFACE_ATTACK_CONTINUATION_PATTERNS",
    "EXTERNAL_REVIEW_SAFE_FRAME_PATTERNS",
    "EXTERNAL_REVIEW_STRONG_SAFE_FRAME_PATTERNS",
    "EXTERNAL_REVIEW_ACTIVE_RISK_PATTERNS",
]
